In [5]:
import pandas as pd

In [9]:
#import csv into dataframe
path = f'Project_3\\NRI_Table_Counties.csv'
raw_df = pd.read_csv(path)
raw_df.head()

,OID_,NRI_ID,STATE,STATEABBRV,STATEFIPS,COUNTY,COUNTYTYPE,COUNTYFIPS,STCOFIPS,POPULATION,...,WNTW_EALS,WNTW_EALR,WNTW_ALRB,WNTW_ALRP,WNTW_ALRA,WNTW_ALR_NPCTL,WNTW_RISKV,WNTW_RISKS,WNTW_RISKR,NRI_VER
0,1,C01001,Alabama,AL,1,Autauga,County,1,1001,58764,...,15.784587,Very Low,2.687716e-07,7.410082e-09,8.725777e-06,10.461158,8494.906508,12.217626,Very Low,March 2023
1,2,C01003,Alabama,AL,1,Baldwin,County,3,1003,231365,...,56.205509,Relatively Moderate,1.268231e-09,2.287120e-08,1.548360e-07,13.339523,65619.701638,52.083996,Relatively Low,March 2023
2,3,C01005,Alabama,AL,1,Barbour,County,5,1005,25160,...,18.632002,Relatively Low,5.788050e-07,2.347236e-08,7.606598e-07,16.125039,15501.730335,19.535476,Very Low,March 2023
3,4,C01007,Alabama,AL,1,Bibb,County,7,1007,22239,...,13.308573,Very Low,9.014679e-07,1.270300e-08,1.202015e-05,16.991643,7496.186940,11.104041,Very Low,March 2023
4,5,C01009,Alabama,AL,1,Blount,County,9,1009,58992,...,23.645930,Relatively Low,5.268425e-07,1.482016e-08,2.002965e-07,12.039616,17175.160729,21.444480,Very Low,March 2023

In [24]:
#select columns to keep
desired_columns = ['STATE', 'STATEABBRV', 'COUNTY', 'COUNTYTYPE', 'POPULATION', 'BUILDVALUE', 'AGRIVALUE', 'AREA', 'NRI_ID', 'TRND_EVNTS', 'TRND_EXPB', 'TRND_EXP_AREA', 'TRND_EALB', 'TRND_EALA', 'TRND_EALS', 'TRND_EALR', 'WFIR_EVNTS', 'WFIR_EXPB', 'WFIR_EXP_AREA', 'WFIR_EALB', 'WFIR_EALA', 'WFIR_EALS', 'WFIR_EALR', 'HRCN_EVNTS', 'HRCN_EXPB', 'HRCN_EXP_AREA', 'HRCN_EALB', 'HRCN_EALA', 'HRCN_EALS', 'HRCN_EALR']
only_cols = raw_df.loc[:, desired_columns]

#replace NaN with 'none'
only_cols['COUNTYTYPE'] = only_cols['COUNTYTYPE'].replace({pd.NA: 'none', 'NaN': 'none'})

#drop all non-county rows
countytype_df = only_cols[only_cols['COUNTYTYPE'].str.contains('County')]
countytype_df.reset_index(drop=True, inplace=True)
countytype_df.head()

,STATE,STATEABBRV,COUNTY,COUNTYTYPE,POPULATION,BUILDVALUE,AGRIVALUE,AREA,NRI_ID,TRND_EVNTS,...,WFIR_EALA,WFIR_EALS,WFIR_EALR,HRCN_EVNTS,HRCN_EXPB,HRCN_EXP_AREA,HRCN_EALB,HRCN_EALA,HRCN_EALS,HRCN_EALR
0,Alabama,AL,Autauga,County,58764,9.123274e+09,24613998.0,610.470508,C01001,39.0,...,1.038512,29.971365,Very Low,13.0,9.121108e+09,610.470508,8.457844e+05,4.678990e+04,66.364029,Relatively Low
1,Alabama,AL,Baldwin,County,231365,4.596848e+10,138089013.0,2047.738775,C01003,68.0,...,250.412183,93.127585,Relatively Moderate,50.0,4.596806e+10,1674.843955,1.736826e+08,1.566622e+06,99.005620,Relatively High
2,Alabama,AL,Barbour,County,25160,4.847697e+09,121075758.0,913.646511,C01005,34.0,...,7.886529,21.094496,Very Low,21.0,4.847697e+09,913.646511,1.525046e+06,4.342251e+05,72.805880,Relatively Low
3,Alabama,AL,Bibb,County,22239,3.146947e+09,4819356.0,632.486798,C01007,27.0,...,0.155020,14.890232,Very Low,11.0,3.146947e+09,632.486798,1.775116e+05,2.442449e+03,49.070471,Very Low
4,Alabama,AL,Blount,County,58992,7.815620e+09,278570859.0,657.196555,C01009,50.0,...,5.534306,18.262806,Very Low,6.0,7.815387e+09,657.196555,1.892511e+05,5.533117e+04,52.399481,Very Low

In [25]:
#drop County type col
clean_df = countytype_df.drop('COUNTYTYPE',axis=1)
clean_df.head()

,STATE,STATEABBRV,COUNTY,POPULATION,BUILDVALUE,AGRIVALUE,AREA,NRI_ID,TRND_EVNTS,TRND_EXPB,...,WFIR_EALA,WFIR_EALS,WFIR_EALR,HRCN_EVNTS,HRCN_EXPB,HRCN_EXP_AREA,HRCN_EALB,HRCN_EALA,HRCN_EALS,HRCN_EALR
0,Alabama,AL,Autauga,58764,9.123274e+09,24613998.0,610.470508,C01001,39.0,9.123274e+09,...,1.038512,29.971365,Very Low,13.0,9.121108e+09,610.470508,8.457844e+05,4.678990e+04,66.364029,Relatively Low
1,Alabama,AL,Baldwin,231365,4.596848e+10,138089013.0,2047.738775,C01003,68.0,4.596848e+10,...,250.412183,93.127585,Relatively Moderate,50.0,4.596806e+10,1674.843955,1.736826e+08,1.566622e+06,99.005620,Relatively High
2,Alabama,AL,Barbour,25160,4.847697e+09,121075758.0,913.646511,C01005,34.0,4.847697e+09,...,7.886529,21.094496,Very Low,21.0,4.847697e+09,913.646511,1.525046e+06,4.342251e+05,72.805880,Relatively Low
3,Alabama,AL,Bibb,22239,3.146947e+09,4819356.0,632.486798,C01007,27.0,3.146947e+09,...,0.155020,14.890232,Very Low,11.0,3.146947e+09,632.486798,1.775116e+05,2.442449e+03,49.070471,Very Low
4,Alabama,AL,Blount,58992,7.815620e+09,278570859.0,657.196555,C01009,50.0,7.815620e+09,...,5.534306,18.262806,Very Low,6.0,7.815387e+09,657.196555,1.892511e+05,5.533117e+04,52.399481,Very Low

In [27]:
#check for Nan Values
Nan_values = clean_df.isna().sum()
Nan_values

STATE               0
STATEABBRV          0
COUNTY              0
POPULATION          0
BUILDVALUE          0
AGRIVALUE           0
AREA                0
NRI_ID              0
TRND_EVNTS          0
TRND_EXPB           0
TRND_EXP_AREA       0
TRND_EALB           0
TRND_EALA           0
TRND_EALS           0
TRND_EALR           0
WFIR_EVNTS       3007
WFIR_EXPB           0
WFIR_EXP_AREA       0
WFIR_EALB           0
WFIR_EALA           0
WFIR_EALS           0
WFIR_EALR           0
HRCN_EVNTS        883
HRCN_EXPB         883
HRCN_EXP_AREA     883
HRCN_EALB         883
HRCN_EALA         883
HRCN_EALS         883
HRCN_EALR           0
dtype: int64